# Generated by Django 2.2.2 on 2019-06-25 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='from_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 16, 32, 11, 996007), null=True),
        ),
    ]
