# Generated by Django 2.2.2 on 2019-06-25 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190625_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='from_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 16, 51, 11, 141134), null=True),
        ),
    ]
