# Generated by Django 2.2.2 on 2019-06-25 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190625_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='from_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Source'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.SourceCity'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 17, 43, 51, 130692), null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Dest'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.DestCity'),
        ),
    ]
