# Generated by Django 2.2.2 on 2019-06-25 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190625_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='from_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 25, 18, 17, 50, 661688), null=True),
        ),
    ]
